name: CD

on:
  release:
    types:
      - created
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: cargo build --release --target armv7-unknown-linux-gnueabihf
