name: CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: armv7-unknown-linux-gnueabihf
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
      - name: Copy
        run: |
          cp target/armv7-unknown-linux-gnueabihf/release/rusty_irrigation_system rusty_irrigation_system
      # - name: Compress
      #   uses: a7ul/tar-action@v1.1.0
      #   id: compress
      #   with:
      #     command: c
      #     files: |
      #       rusty_irrigation_system
      #       build
      #     outPath: rusty_irrigation_system.tar.gz
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          # rusty_irrigation_system.tar.gz
          files: |
            rusty_irrigation_system
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
